name: build

on:
  push:
    branchs: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
      path: |
      ~/go/pkg/mod
      ~/.cache/go-build
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: ${{ runner.os }}-go-
    - run: make deps
    - run: make build
    - run: make artifacts.tgz
    - uses: actions/upload-artifact@v2
      if: !failure()
      with:
        name: artifacts.tgz
        path: ./artifacts.tgz

  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifacts@v2
      with:
        name: artifacts.tgz
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - run: make upload
